name: Build notebooks and publish

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_NUM: '1'
  PY_VER: '3.12'
  JULIA_CONDAPKG_BACKEND: 'Null'
  JULIA_CI: 'true'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Setup Python
      uses: actions/setup-python@v6
      id: cp
      with:
        python-version: ${{ env.PY_VER }}
        cache: 'pip'
    - name: Install python packages
      run: pip install -r requirements.txt
    - name: Read Julia version
      uses: SebRollen/toml-action@v1.2.0
      id: read_toml
      with:
        file: 'Manifest.toml'
        field: 'julia_version'
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ steps.read_toml.outputs.value }}
    - name: Cache Julia packages
      uses: actions/cache@v4
      id: cache-julia
      with:
        save-always: 'true'
        path: |
          ~/.julia
          !~/.julia/registries
        key: ${{ runner.os }}-julia-${{ env.CACHE_NUM }}-${{ hashFiles('Manifest.toml')}}
        restore-keys: |
          ${{ runner.os }}-julia-${{ env.CACHE_NUM }}-
    - name: Install Julia packages
      if: ${{ steps.cache-julia.outputs.cache-hit != 'true' }}
      env:
        PYTHON: ${{ steps.cp.outputs.python-path }}
      shell: julia --project=@. --color=yes {0}
      run: |
        using Pkg, Dates
        Pkg.instantiate()
        Pkg.precompile()
        Pkg.gc(collect_delay=Day(0))
    - name: Run script
      run: julia --project=@. --color=yes main.jl
